# Generated by Django 3.2.3 on 2021-05-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('math', 'Math'), ('riddle', 'Riddle')], default='CATEGORY_CHOICES.math', max_length=10),
        ),
    ]
