# Generated by Django 3.2.3 on 2021-05-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(limit_choices_to=models.Q(('user', 'user.User')), on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='question.category'),
        ),
    ]
